# Generated by Django 4.1.5 on 2023-01-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_content_order_module_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
    ]
