# Generated by Django 4.1.5 on 2023-01-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
